apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "omero-web.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "omero-web.name" . }}
    helm.sh/chart: {{ include "omero-web.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "omero-web.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "omero-web.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        # Autorestart when the configmap changes!
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- if .Values.securityContext.enabled }}
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 4080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.prefix }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.prefix }}
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          {{- if .Values.config.defaultWebapps }}
            - name: omero-web-config
              mountPath: /opt/omero/web/config/01-default-webapps.omero
              subPath: 01-default-webapps.omero
          {{- end }}
            - name: omero-web-config
              mountPath: /opt/omero/web/config/web.omero
              subPath: web.omero
            - name: omero-web-var
              mountPath: /opt/omero/web/OMERO.web/var
      volumes:
        - name: omero-web-config
          configMap:
            name: omero-web-config
        - name: omero-web-var
          emptyDir: {}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
